---
title: "GTEx Parsing"
author: "Matthew Berginski"
date: "April 9, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)

library(BerginskiRMisc)
library(DarkKinaseTools)
```

# Download GTEx Data

```{r download}
GTEx_file = here('GTEx/GTEx_Analysis_2016-01-15_v7_RNASeQCv1.1.8_gene_median_tpm.gct.gz')

if (! file.exists(GTEx_file)) {
  download.file(url = "https://storage.googleapis.com/gtex_analysis_v7/rna_seq_data/GTEx_Analysis_2016-01-15_v7_RNASeQCv1.1.8_gene_median_tpm.gct.gz",
                GTEx_file)
}

GTEx_data = read_delim(GTEx_file,delim="\t",skip=2)
```

# Kinase Extraction

```{r kinase_filtering}
kinase_data_tidy = GTEx_data %>%
  right_join(all_kinases %>% select('class','symbol'), 
             by=c('Description'='symbol')) %>%
  select(-gene_id) %>%
  rename(symbol=Description) %>%
  gather("tissue_type","TPM",-symbol,-class) %>%
  filter(!is.na(TPM))

#Removing some tissue types that don't match up with body parts
kinase_data_tidy = kinase_data_tidy %>%
  filter(tissue_type != "Cells - EBV-transformed lymphocytes",
         tissue_type != "Cells - Transformed fibroblasts")

GTEx_to_gganato = read_rds(here('GTEx/GTEx_tissue_to_gganato.rds'))

kinase_data_tidy = kinase_data_tidy %>%
  left_join(GTEx_to_gganato)
```

```{r kinase_expression_levels}
kinase_mean_expression = kinase_data_tidy %>%
  group_by(symbol,class) %>%
  summarise(mean_expression = mean(TPM))

kinase_percentile_per_tissue = kinase_data_tidy %>%
  group_by(tissue_type) %>%
  mutate(kinase_percentile = 100*round(percent_rank(TPM),2)) %>%
  write_csv(here('GTEx/GTex_kinase_percentiles.csv'))
```

```{r draw kinase percentile graphs}
dark_kinase_percentiles = kinase_percentile_per_tissue %>% 
  filter(class == "Dark") %>% 
  #This bit of code adds a column for the positional index of the ranked kinase
  #percentile, will be used for plotting purposes
  group_by(symbol) %>% 
  arrange(desc(kinase_percentile)) %>% 
  mutate(percentile_index = 1:n()) %>% 
  ungroup() %>%
  
  #Comparible bit to add an organ percentile index
  group_by(tissue_type) %>%
  arrange(desc(kinase_percentile)) %>%
  mutate(organ_percentile_index = 1:n()) %>%
  ungroup()

dir.create(here('GTEx/kinase_percentile_graphs'))

for (this_kinase in unique(dark_kinase_percentiles$symbol)) {
  full_kinase_data = dark_kinase_percentiles %>%
    filter(symbol == this_kinase)
  
  kinase_percentile_plot = ggplot(dark_kinase_percentiles, 
                                  aes(x=percentile_index,y=kinase_percentile, group=symbol)) +
    geom_line(alpha=0.05) +
    ylim(c(0,100)) +
    geom_line(data=full_kinase_data, aes(x=percentile_index,y=kinase_percentile)) +
    labs(x="Organ Index", y="Kinase Percentile") +
    theme_berginski() +
    theme(text = element_text(size=20),
          plot.margin = margin(0,0,0,0, "cm"))
  ggsave(here('GTEx/kinase_percentile_graphs',paste0(this_kinase,'.svg')))
}
```
```{r}
library(gganatogram)
dir.create(here('GTEx/top_5_anatograms'))
for (this_kinase in unique(dark_kinase_percentiles$symbol)) {
  top_organ_data = dark_kinase_percentiles %>%
    filter(symbol == this_kinase) %>%
    arrange(desc(kinase_percentile)) %>%
    slice(1:5)
  
  gganatogram(data=hgMale_key %>% filter(organ %in% top_organ_data$organ),
                sex = 'Male') + theme_void() +
      theme(plot.margin = margin(0, 0, 0, 0, "cm"))
  ggsave(here('GTEx/top_5_anatograms',paste0(this_kinase,'-male.svg')))
  
  gganatogram(data=hgFemale_key %>% filter(organ %in% top_organ_data$organ),
              sex = 'Female') + theme_void() +
    theme(plot.margin = margin(0, 0, 0, 0, "cm"))
  ggsave(here('GTEx/top_5_anatograms',paste0(this_kinase,'-female.svg')))
}
```

```{r}
calc_cor <- function(kinase_1, kinase_2, percentile_data = kinase_percentile_per_tissue) {
  library(broom)
  kinase_1_percentiles = (kinase_percentile_per_tissue %>% filter(symbol == kinase_1))$kinase_percentile
  kinase_2_percentiles = (kinase_percentile_per_tissue %>% filter(symbol == kinase_2))$kinase_percentile
  return(tidy(cor.test(kinase_1_percentiles,kinase_2_percentiles))$estimate)
}

calc_mean_diff <- function(kinase_1, kinase_2, percentile_data = kinase_percentile_per_tissue) {
  kinase_1_percentiles = (kinase_percentile_per_tissue %>% filter(symbol == kinase_1))$kinase_percentile
  kinase_2_percentiles = (kinase_percentile_per_tissue %>% filter(symbol == kinase_2))$kinase_percentile
  return(mean(abs(kinase_1_percentiles - kinase_2_percentiles)))
}

library(tictoc)
library(furrr)
plan(multiprocess)
tic()
kinase_expression_correlations = crossing(kinase_1 = unique(kinase_percentile_per_tissue$symbol),
                                          kinase_2 = unique(kinase_percentile_per_tissue$symbol)) %>%
  filter(kinase_1 != kinase_2) %>%
  mutate(kinase_percentile_cor = future_map2_dbl(kinase_1, kinase_2, calc_cor)) %>%
  mutate(mean_diff = future_map2_dbl(kinase_1, kinase_2, calc_mean_diff)) %>%
  mutate(kinase_percentile_cor = round(kinase_percentile_cor,2)) %>%
  mutate(mean_diff = round(mean_diff,2)) %>%
  left_join(all_kinases %>% select(symbol,class), by=c("kinase_1"="symbol")) %>%
  rename(kinase_1_class = class) %>%
  left_join(all_kinases %>% select(symbol,class), by=c("kinase_2"="symbol")) %>%
  rename(kinase_2_class = class) %>%
  write_rds(here('GTEx/GTEx_expression_correlations.rds'))
identity()
toc()
```

```{r}
GTEx_expression_correlations %>%
  filter(kinase_1_class == "Dark") %>%
  write_rds(here('GTEx/GTEx_expression_correlations_DK_only.rds'))
```

```{r}


temp = kinase_expression_correlations %>% 
  filter(kinase_1_class == "Dark", kinase_2_class == "Light") %>% 
  filter(kinase_1 == "MKNK2") %>%
  arrange(desc(cor_signf))

percentile_comparisons = kinase_percentile_per_tissue %>% 
  filter(symbol %in% c(temp$kinase_2[1:5])) %>% 
  left_join(kinase_percentile_per_tissue %>% 
              filter(symbol == "MKNK2") %>%
              select(tissue_type,kinase_percentile) %>%
              rename(DK_percentile = kinase_percentile))

library(BerginskiRMisc)
ggplot(percentile_comparisons, aes(x=DK_percentile,y=kinase_percentile, color=symbol)) + 
  geom_point() +
  xlim(0,100) + 
  ylim(0,100) + theme_berginski()
```

```{r}
highly_expressed_DK_tissue_counts = highly_expressed_DK %>%
  group_by(tissue_type) %>%
  summarise(DK_count = n())

highly_expressed_DK_gene_counts = highly_expressed_DK %>%
  group_by(symbol) %>%
  summarise(tissue_count = n())
```

```{r}
kinase_percentile_sd = kinase_percentile_per_tissue %>% 
  group_by(symbol,class) %>% 
  summarise(percentile_sd = sd(kinase_percentile), 
            mean_percentile = mean(kinase_percentile), 
            percentile_cv = mean_percentile/percentile_sd) %>% 
  filter(class == "Dark", mean_percentile >= 25)
```
